version: "3"

services:
    order-service:
        image: webdevops/php:8.1
        # You should comment out if your environment is windows.
        # platform: linux/x86_64
        networks:
            - anser_project_network
        ports:
            - 8082:8080
        working_dir: /app
        environment:
            - WEB_DOCUMENT_ROOT=/app/public
            - PHP_MEMORY_LIMIT=2048M
            - PHP_MAX_EXECUTION_TIME=300
            - PHP_POST_MAX_SIZE=2048M
            - PHP_UPLOAD_MAX_FILESIZE=2048M
        volumes:
            - './app:/app'
        # For Mac
        command: >
            bash -c "chmod 776 ./start_service.sh && ./start_service.sh"
        # For Windows
        # command: > 
        #     bash -c "chmod 776 ./start_service.sh && sed -i -e 's/\r$$//' ./start_service.sh && ./start_service.sh"
    order_DB:
        image: postgres:11.12
        networks:
            - anser_project_network
        environment:
            POSTGRES_DB: order
            POSTGRES_USER: root
            POSTGRES_PASSWORD: root
        ports:
            - 8320:5432
        volumes:
            - order-db-data:/var/lib/postgresql/data/
        command:
            [
                "postgres",
                "-c",
                "logging_collector=on",
                "-c",
                "log_destination=stderr",
                "-c",
                "max_connections=50000"
            ]
    # order_test_DB:
    #     image: postgres:11.12
    #     networks:
    #         - anser_project_network
    #     environment:
    #         POSTGRES_DB: order
    #         POSTGRES_USER: root
    #         POSTGRES_PASSWORD: root
    #     ports:
    #         - 8321:5432
    #     volumes:
    #         - ./order-test-db-data:/var/lib/postgresql/data/
    #     command:
    #         [
    #             "postgres",
    #             "-c",
    #             "logging_collector=on",
    #             "-c",
    #             "log_destination=stderr",
    #             "-c",
    #             "max_connections=50000"
    #         ]
networks:
    anser_project_network:
        external: true
volumes:
    order-db-data: